# prettier-ignore
services:
  storefy_db:
    image: mysql:8.0
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql  # Volumen separado para storefy_db
  storefy_db_test:
    image: mysql:8.0
    volumes:
      - db_data_test:/var/lib/mysql  # Volumen separado para storefy_db_test
    ports:
      - "3313:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  db_data:  # Declaración del volumen para storefy_db
  db_data_test:  # Declaración del volumen para storefy_db_test
