# prettier-ignore
name: CI Test

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3313:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=10
        env:
          MYSQL_DATABASE: storefy_db_test
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_USER: franklinserif
          MYSQL_PASSWORD: 1234
        # Optional if you need to seed your database with initial data
        volumes:
          - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..60}; do  # Increase retries to 60
            if mysqladmin ping -h 127.0.0.1 --silent; then
              break
            fi
            echo 'Waiting for MySQL...'
            sleep 2  # Increase sleep time to 2 seconds
          done

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
        env:
          CI: true  # Forcing CI mode for Jest
          MYSQL_HOST: 127.0.0.1  # Set this in your test config

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          branch: main
          title: "Merge dev into main"
          body: "Automated PR to merge changes from dev into main."
          labels: "auto-generated"
          assignees: "franklinsrr"
          reviewers: "franklinsrr"
