name: Formatting and checking code

on:
    push:
        branches:
            - main
            - develop
        paths:
            - 'src/**'
    pull_request:
        branches:
            - main
            - develop
        paths:
            - 'src/**'
    workflow_dispatch:

jobs:
    lint:
        defaults:
            run:
                shell: bash
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.PAT }}

            - name: Check repository
              run: echo "Checking code"

            - name: Install dependencies
              run: npm install

            - name: Format code
              run: npm run prettier

            - name: Linter
              run: npx eslint

            - name: Check for changes
              id: git-check
              run: |
                  git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

            - name: Configure Git
              if: steps.git-check.outputs.changes == 'true'
              run: |
                  git config --local user.name "GitHub Action"
                  git config --local user.email "action@github.com"

            - name: Commit and push changes
              if: steps.git-check.outputs.changes == 'true'
              run: |
                  git add .
                  git commit -m "Format code and fix linting issues"
                  git push
